CREATE TABLE STUDENT(
   		    STUDENTRNO INT PRIMARY KEY     NOT NULL,
                    STUDENTNAME           VARCHAR(50) NOT NULL,
                    STUDENTAGE            INT     NOT NULL,
                    STUDENTADDRESS        VARCHAR(50)
                    );
                 
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (101, 'Jayashree', 27, 'Karamballi');
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (102, 'Akshatha', 26, 'Perdoor');
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (103, 'Akshataha Naik', 27, 'Hebri');
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (104, 'Prajna', 27, 'Kinnimulki');
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (105, 'Anusha', 27, 'Malpe');
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (106, 'Shilpa', 26, 'Athradi');


SELECT STUDENTRNO, STUDENTNAME FROM STUDENT;
UPDATE STUDENT SET STUDENTAGE = 26 WHERE STUDENTRNO = 103;
DELETE FROM STUDENT WHERE ID = 106;

